/**
 * GitHub Issues integration for SDD Tasks
 */

export interface ParsedTask {
  id: string;
  title: string;
  files: string[];
  dependencies: string[];
  story?: string;
  parallel: boolean;
  done: boolean;
}

export function parseTasksMarkdown(content: string): ParsedTask[] {
  const tasks: ParsedTask[] = [];
  const lines = content.split('\n');

  for (const line of lines) {
    const match = line.match(/^- \[([ xX])\] (T\d+)\s*(\[P\])?\s*(\[US\d+\])?\s*(.+)/);
    if (!match) continue;

    const [, done, id, parallel, story, title] = match;
    const files = (title.match(/`([^`]+)`/g) || []).map(f => f.replace(/`/g, ''));

    tasks.push({
      id,
      title: title.replace(/`[^`]+`/g, '').trim(),
      files,
      dependencies: [],
      story: story?.replace(/[[\]]/g, ''),
      parallel: !!parallel,
      done: done !== ' ',
    });
  }

  return tasks;
}

export function taskToIssueBody(task: ParsedTask, projectName: string): string {
  let body = `## ${task.id}: ${task.title}\n\n`;
  body += `**Project**: ${projectName}\n`;
  if (task.story) body += `**Story**: ${task.story}\n`;
  if (task.files.length) body += `**Files**: ${task.files.map(f => `\`${f}\``).join(', ')}\n`;
  if (task.parallel) body += `**Parallelizable**: Yes\n`;
  body += `\n---\n*Generated by Inkwell SDD*`;
  return body;
}

export async function createGitHubIssue(
  repo: string,
  token: string,
  title: string,
  body: string,
  labels?: string[],
): Promise<{ number: number; url: string }> {
  const res = await fetch(`https://api.github.com/repos/${repo}/issues`, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${token}`,
      'Content-Type': 'application/json',
      'Accept': 'application/vnd.github+json',
    },
    body: JSON.stringify({ title, body, labels }),
  });

  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.message || `GitHub API error: ${res.status}`);
  }

  const data = await res.json();
  return { number: data.number, url: data.html_url };
}

export function updateTasksWithIssueLinks(content: string, links: Map<string, number>): string {
  let updated = content;
  for (const [taskId, issueNum] of links) {
    updated = updated.replace(
      new RegExp(`(- \\[[ xX]\\] ${taskId})`),
      `$1 [#${issueNum}]`
    );
  }
  return updated;
}
